const o = "Nebyla nalezena žádná leasingová smlouva", n = "Nejprve nastavte integraci Leasing KM Calculator.", t = "Tato smlouva již neexistuje. Vyberte ji znovu.", e = "Načítání…", no = "–", s = "Konec smlouvy {date}", c = "podle plánu", a = "nad cílem", i = "limit ohrožen", l = "cíl {p} %", r = "Ujetá vzdálenost", m = "{a} / {b} dní", d = "Cíl a skutečnost", v = "Smluvní rok {n}", u = "Prognóza", k = "Zbývá podle cíle", p = "Odchylka dnes", g = "Odchylka na konci měsíce", y = "Skutečnost za den", b = "Zbývající kilometry", C = "Ujeto", z = "Odchylka", D = "Limit", T = "Konec smluvního roku", h = "Konec smlouvy", O = "Očekávaný rozdíl", j = "Do konce smluvního roku", Y = "Do konce smlouvy", L = "cíl {v}", R = "do konce smlouvy", E = "průměr celé smlouvy", F = "posledních 30 dní", K = "posledních 90 dní", N = "nad limitem", Z = "v limitu", w = "nad denním cílem", x = "pod denním cílem", A = "roční nájezd ohrožen", B = "roční nájezd bezpečný", P = "limit bude překročen", S = "limit dodržen", U = "Leasingová smlouva", f = "Název", I = "Omezit procenta na 100 %", M = "Zobrazit smluvní rok", V = "Zobrazit prognózu", q = "Vyúčtování", G = "Prognóza na konci smlouvy", H = "Při cílovém tempu", J = "Do tolerance", Q = "očekává se doplatek", W = "očekává se náhrada", X = "není co vyúčtovat", _ = "tolerance dodržena", $ = "tolerance překročena", oo = "Zobrazit vyúčtování", to = {
  noInstanceTitle: o,
  noInstanceBody: n,
  missing: t,
  loading: e,
  unknown: "–",
  contractEnd: s,
  badgeOk: c,
  badgeOver: a,
  badgeRisk: i,
  gaugeSub: l,
  progressLabel: r,
  progressDays: m,
  sectionTargetActual: d,
  sectionContractYear: v,
  sectionForecast: u,
  sectionRemaining: k,
  mDeviationToday: p,
  mDeviationMonth: g,
  mDailyActual: y,
  mRemainingTotal: b,
  mContractYearDriven: C,
  mContractYearDeviation: z,
  mContractYearAllowance: D,
  mForecastContractYear: T,
  mForecastContractEnd: h,
  mForecastDeviation: O,
  mRemainingContractYear: j,
  mRemainingContractEnd: Y,
  subTarget: L,
  subUntilContractEnd: R,
  subBasisTotal: E,
  subBasis30: F,
  subBasis90: K,
  overLimit: N,
  withinLimit: Z,
  pillOverDaily: w,
  pillUnderDaily: x,
  pillYearRisk: A,
  pillYearSafe: B,
  pillLimitExceeded: P,
  pillLimitOk: S,
  editorDevice: U,
  editorTitle: f,
  editorClamp: I,
  editorContractYear: M,
  editorForecast: V,
  sectionCosts: q,
  mCostForecast: G,
  mCostAtTarget: H,
  mKmToTolerance: J,
  costPay: Q,
  costRefund: W,
  costNone: X,
  pillToleranceOk: _,
  pillToleranceExceeded: $,
  editorCosts: oo
};
export {
  c as badgeOk,
  a as badgeOver,
  i as badgeRisk,
  s as contractEnd,
  X as costNone,
  Q as costPay,
  W as costRefund,
  to as default,
  I as editorClamp,
  M as editorContractYear,
  oo as editorCosts,
  U as editorDevice,
  V as editorForecast,
  f as editorTitle,
  l as gaugeSub,
  e as loading,
  D as mContractYearAllowance,
  z as mContractYearDeviation,
  C as mContractYearDriven,
  H as mCostAtTarget,
  G as mCostForecast,
  y as mDailyActual,
  g as mDeviationMonth,
  p as mDeviationToday,
  h as mForecastContractEnd,
  T as mForecastContractYear,
  O as mForecastDeviation,
  J as mKmToTolerance,
  Y as mRemainingContractEnd,
  j as mRemainingContractYear,
  b as mRemainingTotal,
  t as missing,
  n as noInstanceBody,
  o as noInstanceTitle,
  N as overLimit,
  P as pillLimitExceeded,
  S as pillLimitOk,
  w as pillOverDaily,
  $ as pillToleranceExceeded,
  _ as pillToleranceOk,
  x as pillUnderDaily,
  A as pillYearRisk,
  B as pillYearSafe,
  m as progressDays,
  r as progressLabel,
  v as sectionContractYear,
  q as sectionCosts,
  u as sectionForecast,
  k as sectionRemaining,
  d as sectionTargetActual,
  F as subBasis30,
  K as subBasis90,
  E as subBasisTotal,
  L as subTarget,
  R as subUntilContractEnd,
  no as unknown,
  Z as withinLimit
};
