const n = "Nebyla nalezena žádná leasingová smlouva", o = "Nejprve nastavte integraci Leasing KM Calculator.", t = "Tato smlouva již neexistuje. Vyberte ji znovu.", e = "Načítání…", q = "–", s = "Konec smlouvy {date}", c = "podle plánu", a = "nad cílem", i = "limit ohrožen", l = "cíl {p} %", r = "Ujetá vzdálenost", m = "{a} / {b} dní", d = "Cíl a skutečnost", u = "Smluvní rok {n}", v = "Prognóza", p = "Zbývá podle cíle", k = "Odchylka dnes", g = "Odchylka na konci měsíce", b = "Skutečnost za den", y = "Zbývající kilometry", z = "Ujeto", C = "Odchylka", D = "Limit", h = "Konec smluvního roku", j = "Konec smlouvy", O = "Očekávaný rozdíl", Y = "Do konce smluvního roku", L = "Do konce smlouvy", T = "cíl {v}", R = "do konce smlouvy", E = "průměr celé smlouvy", F = "posledních 30 dní", w = "posledních 90 dní", B = "nad limitem", K = "v limitu", N = "nad denním cílem", S = "pod denním cílem", U = "roční nájezd ohrožen", Z = "roční nájezd bezpečný", x = "limit bude překročen", A = "limit dodržen", f = "Leasingová smlouva", I = "Název", M = "Omezit procenta na 100 %", P = "Zobrazit smluvní rok", V = "Zobrazit prognózu", G = {
  noInstanceTitle: n,
  noInstanceBody: o,
  missing: t,
  loading: e,
  unknown: "–",
  contractEnd: s,
  badgeOk: c,
  badgeOver: a,
  badgeRisk: i,
  gaugeSub: l,
  progressLabel: r,
  progressDays: m,
  sectionTargetActual: d,
  sectionContractYear: u,
  sectionForecast: v,
  sectionRemaining: p,
  mDeviationToday: k,
  mDeviationMonth: g,
  mDailyActual: b,
  mRemainingTotal: y,
  mContractYearDriven: z,
  mContractYearDeviation: C,
  mContractYearAllowance: D,
  mForecastContractYear: h,
  mForecastContractEnd: j,
  mForecastDeviation: O,
  mRemainingContractYear: Y,
  mRemainingContractEnd: L,
  subTarget: T,
  subUntilContractEnd: R,
  subBasisTotal: E,
  subBasis30: F,
  subBasis90: w,
  overLimit: B,
  withinLimit: K,
  pillOverDaily: N,
  pillUnderDaily: S,
  pillYearRisk: U,
  pillYearSafe: Z,
  pillLimitExceeded: x,
  pillLimitOk: A,
  editorDevice: f,
  editorTitle: I,
  editorClamp: M,
  editorContractYear: P,
  editorForecast: V
};
export {
  c as badgeOk,
  a as badgeOver,
  i as badgeRisk,
  s as contractEnd,
  G as default,
  M as editorClamp,
  P as editorContractYear,
  f as editorDevice,
  V as editorForecast,
  I as editorTitle,
  l as gaugeSub,
  e as loading,
  D as mContractYearAllowance,
  C as mContractYearDeviation,
  z as mContractYearDriven,
  b as mDailyActual,
  g as mDeviationMonth,
  k as mDeviationToday,
  j as mForecastContractEnd,
  h as mForecastContractYear,
  O as mForecastDeviation,
  L as mRemainingContractEnd,
  Y as mRemainingContractYear,
  y as mRemainingTotal,
  t as missing,
  o as noInstanceBody,
  n as noInstanceTitle,
  B as overLimit,
  x as pillLimitExceeded,
  A as pillLimitOk,
  N as pillOverDaily,
  S as pillUnderDaily,
  U as pillYearRisk,
  Z as pillYearSafe,
  m as progressDays,
  r as progressLabel,
  u as sectionContractYear,
  v as sectionForecast,
  p as sectionRemaining,
  d as sectionTargetActual,
  F as subBasis30,
  w as subBasis90,
  E as subBasisTotal,
  T as subTarget,
  R as subUntilContractEnd,
  q as unknown,
  K as withinLimit
};
