const o = "No se encontró ningún contrato de leasing", t = "Configura primero la integración Leasing KM Calculator.", e = "Este contrato ya no existe. Vuelve a seleccionarlo.", n = "Cargando…", z = "–", a = "Fin del contrato {date}", i = "según lo previsto", s = "por encima del objetivo", c = "límite en riesgo", r = "objetivo {p} %", l = "Kilometraje recorrido", d = "{a} / {b} días", m = "Objetivo y real", g = "Año de contrato {n}", v = "Previsión", p = "Restante sobre el objetivo", b = "Desviación hoy", u = "Desviación a fin de mes", C = "Real por día", D = "Kilómetros restantes", j = "Recorrido", y = "Desviación", R = "Límite", Y = "Fin del año de contrato", f = "Fin del contrato", k = "Diferencia prevista", F = "Hasta fin del año de contrato", L = "Hasta el fin del contrato", T = "objetivo {v}", E = "hasta el fin del contrato", O = "media de todo el contrato", h = "últimos 30 días", w = "últimos 90 días", A = "por encima del límite", B = "dentro del límite", M = "por encima del objetivo diario", x = "por debajo del objetivo diario", K = "kilometraje anual en riesgo", H = "kilometraje anual seguro", I = "se superará el límite", S = "límite respetado", U = "Contrato de leasing", N = "Título", P = "Limitar el porcentaje al 100 %", V = "Mostrar el año de contrato", q = "Mostrar la previsión", G = {
  noInstanceTitle: o,
  noInstanceBody: t,
  missing: e,
  loading: n,
  unknown: "–",
  contractEnd: a,
  badgeOk: i,
  badgeOver: s,
  badgeRisk: c,
  gaugeSub: r,
  progressLabel: l,
  progressDays: d,
  sectionTargetActual: m,
  sectionContractYear: g,
  sectionForecast: v,
  sectionRemaining: p,
  mDeviationToday: b,
  mDeviationMonth: u,
  mDailyActual: C,
  mRemainingTotal: D,
  mContractYearDriven: j,
  mContractYearDeviation: y,
  mContractYearAllowance: R,
  mForecastContractYear: Y,
  mForecastContractEnd: f,
  mForecastDeviation: k,
  mRemainingContractYear: F,
  mRemainingContractEnd: L,
  subTarget: T,
  subUntilContractEnd: E,
  subBasisTotal: O,
  subBasis30: h,
  subBasis90: w,
  overLimit: A,
  withinLimit: B,
  pillOverDaily: M,
  pillUnderDaily: x,
  pillYearRisk: K,
  pillYearSafe: H,
  pillLimitExceeded: I,
  pillLimitOk: S,
  editorDevice: U,
  editorTitle: N,
  editorClamp: P,
  editorContractYear: V,
  editorForecast: q
};
export {
  i as badgeOk,
  s as badgeOver,
  c as badgeRisk,
  a as contractEnd,
  G as default,
  P as editorClamp,
  V as editorContractYear,
  U as editorDevice,
  q as editorForecast,
  N as editorTitle,
  r as gaugeSub,
  n as loading,
  R as mContractYearAllowance,
  y as mContractYearDeviation,
  j as mContractYearDriven,
  C as mDailyActual,
  u as mDeviationMonth,
  b as mDeviationToday,
  f as mForecastContractEnd,
  Y as mForecastContractYear,
  k as mForecastDeviation,
  L as mRemainingContractEnd,
  F as mRemainingContractYear,
  D as mRemainingTotal,
  e as missing,
  t as noInstanceBody,
  o as noInstanceTitle,
  A as overLimit,
  I as pillLimitExceeded,
  S as pillLimitOk,
  M as pillOverDaily,
  x as pillUnderDaily,
  K as pillYearRisk,
  H as pillYearSafe,
  d as progressDays,
  l as progressLabel,
  g as sectionContractYear,
  v as sectionForecast,
  p as sectionRemaining,
  m as sectionTargetActual,
  h as subBasis30,
  w as subBasis90,
  O as subBasisTotal,
  T as subTarget,
  E as subUntilContractEnd,
  z as unknown,
  B as withinLimit
};
