const o = "No se encontró ningún contrato de leasing", t = "Configura primero la integración Leasing KM Calculator.", e = "Este contrato ya no existe. Vuelve a seleccionarlo.", n = "Cargando…", to = "–", a = "Fin del contrato {date}", s = "según lo previsto", i = "por encima del objetivo", c = "límite en riesgo", r = "objetivo {p} %", l = "Kilometraje recorrido", d = "{a} / {b} días", m = "Objetivo y real", p = "Año de contrato {n}", v = "Previsión", g = "Restante sobre el objetivo", u = "Desviación hoy", b = "Desviación a fin de mes", C = "Real por día", D = "Kilómetros restantes", j = "Recorrido", T = "Desviación", f = "Límite", y = "Fin del año de contrato", R = "Fin del contrato", k = "Diferencia prevista", F = "Hasta fin del año de contrato", L = "Hasta el fin del contrato", Y = "objetivo {v}", E = "hasta el fin del contrato", A = "media de todo el contrato", O = "últimos 30 días", M = "últimos 90 días", h = "por encima del límite", q = "dentro del límite", w = "por encima del objetivo diario", x = "por debajo del objetivo diario", B = "kilometraje anual en riesgo", K = "kilometraje anual seguro", H = "se superará el límite", P = "límite respetado", I = "Contrato de leasing", N = "Título", S = "Limitar el porcentaje al 100 %", U = "Mostrar el año de contrato", V = "Mostrar la previsión", z = "Liquidación", G = "Previsión fin del contrato", J = "Al ritmo objetivo", Q = "Hasta la tolerancia", W = "pago previsto", X = "reembolso previsto", Z = "nada que liquidar", _ = "tolerancia respetada", $ = "tolerancia superada", oo = "Mostrar la liquidación", eo = {
  noInstanceTitle: o,
  noInstanceBody: t,
  missing: e,
  loading: n,
  unknown: "–",
  contractEnd: a,
  badgeOk: s,
  badgeOver: i,
  badgeRisk: c,
  gaugeSub: r,
  progressLabel: l,
  progressDays: d,
  sectionTargetActual: m,
  sectionContractYear: p,
  sectionForecast: v,
  sectionRemaining: g,
  mDeviationToday: u,
  mDeviationMonth: b,
  mDailyActual: C,
  mRemainingTotal: D,
  mContractYearDriven: j,
  mContractYearDeviation: T,
  mContractYearAllowance: f,
  mForecastContractYear: y,
  mForecastContractEnd: R,
  mForecastDeviation: k,
  mRemainingContractYear: F,
  mRemainingContractEnd: L,
  subTarget: Y,
  subUntilContractEnd: E,
  subBasisTotal: A,
  subBasis30: O,
  subBasis90: M,
  overLimit: h,
  withinLimit: q,
  pillOverDaily: w,
  pillUnderDaily: x,
  pillYearRisk: B,
  pillYearSafe: K,
  pillLimitExceeded: H,
  pillLimitOk: P,
  editorDevice: I,
  editorTitle: N,
  editorClamp: S,
  editorContractYear: U,
  editorForecast: V,
  sectionCosts: z,
  mCostForecast: G,
  mCostAtTarget: J,
  mKmToTolerance: Q,
  costPay: W,
  costRefund: X,
  costNone: Z,
  pillToleranceOk: _,
  pillToleranceExceeded: $,
  editorCosts: oo
};
export {
  s as badgeOk,
  i as badgeOver,
  c as badgeRisk,
  a as contractEnd,
  Z as costNone,
  W as costPay,
  X as costRefund,
  eo as default,
  S as editorClamp,
  U as editorContractYear,
  oo as editorCosts,
  I as editorDevice,
  V as editorForecast,
  N as editorTitle,
  r as gaugeSub,
  n as loading,
  f as mContractYearAllowance,
  T as mContractYearDeviation,
  j as mContractYearDriven,
  J as mCostAtTarget,
  G as mCostForecast,
  C as mDailyActual,
  b as mDeviationMonth,
  u as mDeviationToday,
  R as mForecastContractEnd,
  y as mForecastContractYear,
  k as mForecastDeviation,
  Q as mKmToTolerance,
  L as mRemainingContractEnd,
  F as mRemainingContractYear,
  D as mRemainingTotal,
  e as missing,
  t as noInstanceBody,
  o as noInstanceTitle,
  h as overLimit,
  H as pillLimitExceeded,
  P as pillLimitOk,
  w as pillOverDaily,
  $ as pillToleranceExceeded,
  _ as pillToleranceOk,
  x as pillUnderDaily,
  B as pillYearRisk,
  K as pillYearSafe,
  d as progressDays,
  l as progressLabel,
  p as sectionContractYear,
  z as sectionCosts,
  v as sectionForecast,
  g as sectionRemaining,
  m as sectionTargetActual,
  O as subBasis30,
  M as subBasis90,
  A as subBasisTotal,
  Y as subTarget,
  E as subUntilContractEnd,
  to as unknown,
  q as withinLimit
};
