const t = "Aucun contrat de leasing trouvé", n = "Configurez d'abord l'intégration Leasing KM Calculator.", e = "Ce contrat n'existe plus. Veuillez le sélectionner à nouveau.", o = "Chargement…", G = "–", s = "Fin du contrat {date}", a = "dans les temps", i = "au-dessus de l'objectif", c = "forfait menacé", r = "objectif {p} %", l = "Kilométrage parcouru", u = "{a} / {b} jours", d = "Objectif et réel", m = "Année de contrat {n}", f = "Prévision", g = "Restant sur base objectif", b = "Écart aujourd'hui", p = "Écart fin de mois", C = "Réel par jour", v = "Kilomètres restants", j = "Parcouru", D = "Écart", F = "Forfait", Y = "Fin de l'année de contrat", k = "Fin du contrat", R = "Différence attendue", T = "Jusqu'à la fin de l'année", y = "Jusqu'à la fin du contrat", A = "objectif {v}", L = "jusqu'à la fin du contrat", h = "moyenne sur tout le contrat", q = "30 derniers jours", E = "90 derniers jours", O = "au-dessus du forfait", w = "dans le forfait", B = "au-dessus de l'objectif quotidien", x = "en dessous de l'objectif quotidien", K = "kilométrage annuel menacé", z = "kilométrage annuel sûr", I = "le forfait sera dépassé", J = "forfait respecté", M = "Contrat de leasing", P = "Titre", S = "Limiter le pourcentage à 100 %", U = "Afficher l'année de contrat", V = "Afficher la prévision", H = {
  noInstanceTitle: t,
  noInstanceBody: n,
  missing: e,
  loading: o,
  unknown: "–",
  contractEnd: s,
  badgeOk: a,
  badgeOver: i,
  badgeRisk: c,
  gaugeSub: r,
  progressLabel: l,
  progressDays: u,
  sectionTargetActual: d,
  sectionContractYear: m,
  sectionForecast: f,
  sectionRemaining: g,
  mDeviationToday: b,
  mDeviationMonth: p,
  mDailyActual: C,
  mRemainingTotal: v,
  mContractYearDriven: j,
  mContractYearDeviation: D,
  mContractYearAllowance: F,
  mForecastContractYear: Y,
  mForecastContractEnd: k,
  mForecastDeviation: R,
  mRemainingContractYear: T,
  mRemainingContractEnd: y,
  subTarget: A,
  subUntilContractEnd: L,
  subBasisTotal: h,
  subBasis30: q,
  subBasis90: E,
  overLimit: O,
  withinLimit: w,
  pillOverDaily: B,
  pillUnderDaily: x,
  pillYearRisk: K,
  pillYearSafe: z,
  pillLimitExceeded: I,
  pillLimitOk: J,
  editorDevice: M,
  editorTitle: P,
  editorClamp: S,
  editorContractYear: U,
  editorForecast: V
};
export {
  a as badgeOk,
  i as badgeOver,
  c as badgeRisk,
  s as contractEnd,
  H as default,
  S as editorClamp,
  U as editorContractYear,
  M as editorDevice,
  V as editorForecast,
  P as editorTitle,
  r as gaugeSub,
  o as loading,
  F as mContractYearAllowance,
  D as mContractYearDeviation,
  j as mContractYearDriven,
  C as mDailyActual,
  p as mDeviationMonth,
  b as mDeviationToday,
  k as mForecastContractEnd,
  Y as mForecastContractYear,
  R as mForecastDeviation,
  y as mRemainingContractEnd,
  T as mRemainingContractYear,
  v as mRemainingTotal,
  e as missing,
  n as noInstanceBody,
  t as noInstanceTitle,
  O as overLimit,
  I as pillLimitExceeded,
  J as pillLimitOk,
  B as pillOverDaily,
  x as pillUnderDaily,
  K as pillYearRisk,
  z as pillYearSafe,
  u as progressDays,
  l as progressLabel,
  m as sectionContractYear,
  f as sectionForecast,
  g as sectionRemaining,
  d as sectionTargetActual,
  q as subBasis30,
  E as subBasis90,
  h as subBasisTotal,
  A as subTarget,
  L as subUntilContractEnd,
  G as unknown,
  w as withinLimit
};
