const t = "Aucun contrat de leasing trouvé", n = "Configurez d'abord l'intégration Leasing KM Calculator.", e = "Ce contrat n'existe plus. Veuillez le sélectionner à nouveau.", o = "Chargement…", nt = "–", s = "Fin du contrat {date}", a = "dans les temps", c = "au-dessus de l'objectif", r = "forfait menacé", i = "objectif {p} %", l = "Kilométrage parcouru", u = "{a} / {b} jours", d = "Objectif et réel", m = "Année de contrat {n}", f = "Prévision", p = "Restant sur base objectif", g = "Écart aujourd'hui", b = "Écart fin de mois", C = "Réel par jour", v = "Kilomètres restants", j = "Parcouru", T = "Écart", D = "Forfait", A = "Fin de l'année de contrat", F = "Fin du contrat", k = "Différence attendue", y = "Jusqu'à la fin de l'année", R = "Jusqu'à la fin du contrat", Y = "objectif {v}", h = "jusqu'à la fin du contrat", L = "moyenne sur tout le contrat", E = "30 derniers jours", O = "90 derniers jours", q = "au-dessus du forfait", w = "dans le forfait", x = "au-dessus de l'objectif quotidien", B = "en dessous de l'objectif quotidien", K = "kilométrage annuel menacé", P = "kilométrage annuel sûr", z = "le forfait sera dépassé", I = "forfait respecté", J = "Contrat de leasing", M = "Titre", S = "Limiter le pourcentage à 100 %", U = "Afficher l'année de contrat", N = "Afficher la prévision", V = "Décompte", G = "Prévision fin de contrat", H = "Au rythme objectif", Q = "Avant la tolérance", W = "supplément attendu", X = "remboursement attendu", Z = "rien à décompter", _ = "tolérance respectée", $ = "tolérance dépassée", tt = "Afficher le décompte", et = {
  noInstanceTitle: t,
  noInstanceBody: n,
  missing: e,
  loading: o,
  unknown: "–",
  contractEnd: s,
  badgeOk: a,
  badgeOver: c,
  badgeRisk: r,
  gaugeSub: i,
  progressLabel: l,
  progressDays: u,
  sectionTargetActual: d,
  sectionContractYear: m,
  sectionForecast: f,
  sectionRemaining: p,
  mDeviationToday: g,
  mDeviationMonth: b,
  mDailyActual: C,
  mRemainingTotal: v,
  mContractYearDriven: j,
  mContractYearDeviation: T,
  mContractYearAllowance: D,
  mForecastContractYear: A,
  mForecastContractEnd: F,
  mForecastDeviation: k,
  mRemainingContractYear: y,
  mRemainingContractEnd: R,
  subTarget: Y,
  subUntilContractEnd: h,
  subBasisTotal: L,
  subBasis30: E,
  subBasis90: O,
  overLimit: q,
  withinLimit: w,
  pillOverDaily: x,
  pillUnderDaily: B,
  pillYearRisk: K,
  pillYearSafe: P,
  pillLimitExceeded: z,
  pillLimitOk: I,
  editorDevice: J,
  editorTitle: M,
  editorClamp: S,
  editorContractYear: U,
  editorForecast: N,
  sectionCosts: V,
  mCostForecast: G,
  mCostAtTarget: H,
  mKmToTolerance: Q,
  costPay: W,
  costRefund: X,
  costNone: Z,
  pillToleranceOk: _,
  pillToleranceExceeded: $,
  editorCosts: tt
};
export {
  a as badgeOk,
  c as badgeOver,
  r as badgeRisk,
  s as contractEnd,
  Z as costNone,
  W as costPay,
  X as costRefund,
  et as default,
  S as editorClamp,
  U as editorContractYear,
  tt as editorCosts,
  J as editorDevice,
  N as editorForecast,
  M as editorTitle,
  i as gaugeSub,
  o as loading,
  D as mContractYearAllowance,
  T as mContractYearDeviation,
  j as mContractYearDriven,
  H as mCostAtTarget,
  G as mCostForecast,
  C as mDailyActual,
  b as mDeviationMonth,
  g as mDeviationToday,
  F as mForecastContractEnd,
  A as mForecastContractYear,
  k as mForecastDeviation,
  Q as mKmToTolerance,
  R as mRemainingContractEnd,
  y as mRemainingContractYear,
  v as mRemainingTotal,
  e as missing,
  n as noInstanceBody,
  t as noInstanceTitle,
  q as overLimit,
  z as pillLimitExceeded,
  I as pillLimitOk,
  x as pillOverDaily,
  $ as pillToleranceExceeded,
  _ as pillToleranceOk,
  B as pillUnderDaily,
  K as pillYearRisk,
  P as pillYearSafe,
  u as progressDays,
  l as progressLabel,
  m as sectionContractYear,
  V as sectionCosts,
  f as sectionForecast,
  p as sectionRemaining,
  d as sectionTargetActual,
  E as subBasis30,
  O as subBasis90,
  L as subBasisTotal,
  Y as subTarget,
  h as subUntilContractEnd,
  nt as unknown,
  w as withinLimit
};
