const t = "Nessun contratto di leasing trovato", o = "Configura prima l'integrazione Leasing KM Calculator.", n = "Questo contratto non esiste più. Selezionalo di nuovo.", i = "Caricamento…", ot = "–", e = "Fine contratto {date}", a = "in linea", s = "sopra l'obiettivo", c = "limite a rischio", r = "obiettivo {p} %", l = "Chilometraggio percorso", m = "{a} / {b} giorni", g = "Obiettivo e reale", u = "Anno contrattuale {n}", d = "Previsione", p = "Residuo su base obiettivo", v = "Scostamento oggi", C = "Scostamento a fine mese", b = "Reale al giorno", T = "Chilometri residui", f = "Percorso", F = "Scostamento", D = "Limite", R = "Fine anno contrattuale", Y = "Fine contratto", h = "Differenza prevista", L = "Fino a fine anno contrattuale", k = "Fino alla fine del contratto", y = "obiettivo {v}", z = "fino alla fine del contratto", A = "media dell'intero contratto", E = "ultimi 30 giorni", O = "ultimi 90 giorni", S = "oltre il limite", M = "entro il limite", w = "sopra l'obiettivo giornaliero", B = "sotto l'obiettivo giornaliero", P = "chilometraggio annuo a rischio", x = "chilometraggio annuo sicuro", I = "il limite sarà superato", K = "limite rispettato", N = "Contratto di leasing", U = "Titolo", Q = "Limita la percentuale al 100 %", j = "Mostra l'anno contrattuale", q = "Mostra la previsione", G = "Conguaglio", H = "Previsione fine contratto", J = "Al ritmo obiettivo", V = "Fino alla tolleranza", W = "pagamento previsto", X = "rimborso previsto", Z = "niente da conguagliare", _ = "tolleranza rispettata", $ = "tolleranza superata", tt = "Mostra il conguaglio", nt = {
  noInstanceTitle: t,
  noInstanceBody: o,
  missing: n,
  loading: i,
  unknown: "–",
  contractEnd: e,
  badgeOk: a,
  badgeOver: s,
  badgeRisk: c,
  gaugeSub: r,
  progressLabel: l,
  progressDays: m,
  sectionTargetActual: g,
  sectionContractYear: u,
  sectionForecast: d,
  sectionRemaining: p,
  mDeviationToday: v,
  mDeviationMonth: C,
  mDailyActual: b,
  mRemainingTotal: T,
  mContractYearDriven: f,
  mContractYearDeviation: F,
  mContractYearAllowance: D,
  mForecastContractYear: R,
  mForecastContractEnd: Y,
  mForecastDeviation: h,
  mRemainingContractYear: L,
  mRemainingContractEnd: k,
  subTarget: y,
  subUntilContractEnd: z,
  subBasisTotal: A,
  subBasis30: E,
  subBasis90: O,
  overLimit: S,
  withinLimit: M,
  pillOverDaily: w,
  pillUnderDaily: B,
  pillYearRisk: P,
  pillYearSafe: x,
  pillLimitExceeded: I,
  pillLimitOk: K,
  editorDevice: N,
  editorTitle: U,
  editorClamp: Q,
  editorContractYear: j,
  editorForecast: q,
  sectionCosts: G,
  mCostForecast: H,
  mCostAtTarget: J,
  mKmToTolerance: V,
  costPay: W,
  costRefund: X,
  costNone: Z,
  pillToleranceOk: _,
  pillToleranceExceeded: $,
  editorCosts: tt
};
export {
  a as badgeOk,
  s as badgeOver,
  c as badgeRisk,
  e as contractEnd,
  Z as costNone,
  W as costPay,
  X as costRefund,
  nt as default,
  Q as editorClamp,
  j as editorContractYear,
  tt as editorCosts,
  N as editorDevice,
  q as editorForecast,
  U as editorTitle,
  r as gaugeSub,
  i as loading,
  D as mContractYearAllowance,
  F as mContractYearDeviation,
  f as mContractYearDriven,
  J as mCostAtTarget,
  H as mCostForecast,
  b as mDailyActual,
  C as mDeviationMonth,
  v as mDeviationToday,
  Y as mForecastContractEnd,
  R as mForecastContractYear,
  h as mForecastDeviation,
  V as mKmToTolerance,
  k as mRemainingContractEnd,
  L as mRemainingContractYear,
  T as mRemainingTotal,
  n as missing,
  o as noInstanceBody,
  t as noInstanceTitle,
  S as overLimit,
  I as pillLimitExceeded,
  K as pillLimitOk,
  w as pillOverDaily,
  $ as pillToleranceExceeded,
  _ as pillToleranceOk,
  B as pillUnderDaily,
  P as pillYearRisk,
  x as pillYearSafe,
  m as progressDays,
  l as progressLabel,
  u as sectionContractYear,
  G as sectionCosts,
  d as sectionForecast,
  p as sectionRemaining,
  g as sectionTargetActual,
  E as subBasis30,
  O as subBasis90,
  A as subBasisTotal,
  y as subTarget,
  z as subUntilContractEnd,
  ot as unknown,
  M as withinLimit
};
