const t = "Nessun contratto di leasing trovato", o = "Configura prima l'integrazione Leasing KM Calculator.", n = "Questo contratto non esiste più. Selezionalo di nuovo.", i = "Caricamento…", G = "–", e = "Fine contratto {date}", a = "in linea", s = "sopra l'obiettivo", c = "limite a rischio", r = "obiettivo {p} %", l = "Chilometraggio percorso", m = "{a} / {b} giorni", g = "Obiettivo e reale", u = "Anno contrattuale {n}", d = "Previsione", v = "Residuo su base obiettivo", p = "Scostamento oggi", b = "Scostamento a fine mese", C = "Reale al giorno", D = "Chilometri residui", f = "Percorso", F = "Scostamento", Y = "Limite", h = "Fine anno contrattuale", L = "Fine contratto", R = "Differenza prevista", T = "Fino a fine anno contrattuale", k = "Fino alla fine del contratto", y = "obiettivo {v}", S = "fino alla fine del contratto", E = "media dell'intero contratto", O = "ultimi 30 giorni", w = "ultimi 90 giorni", A = "oltre il limite", B = "entro il limite", M = "sopra l'obiettivo giornaliero", z = "sotto l'obiettivo giornaliero", x = "chilometraggio annuo a rischio", I = "chilometraggio annuo sicuro", P = "il limite sarà superato", U = "limite rispettato", K = "Contratto di leasing", N = "Titolo", Q = "Limita la percentuale al 100 %", j = "Mostra l'anno contrattuale", q = "Mostra la previsione", H = {
  noInstanceTitle: t,
  noInstanceBody: o,
  missing: n,
  loading: i,
  unknown: "–",
  contractEnd: e,
  badgeOk: a,
  badgeOver: s,
  badgeRisk: c,
  gaugeSub: r,
  progressLabel: l,
  progressDays: m,
  sectionTargetActual: g,
  sectionContractYear: u,
  sectionForecast: d,
  sectionRemaining: v,
  mDeviationToday: p,
  mDeviationMonth: b,
  mDailyActual: C,
  mRemainingTotal: D,
  mContractYearDriven: f,
  mContractYearDeviation: F,
  mContractYearAllowance: Y,
  mForecastContractYear: h,
  mForecastContractEnd: L,
  mForecastDeviation: R,
  mRemainingContractYear: T,
  mRemainingContractEnd: k,
  subTarget: y,
  subUntilContractEnd: S,
  subBasisTotal: E,
  subBasis30: O,
  subBasis90: w,
  overLimit: A,
  withinLimit: B,
  pillOverDaily: M,
  pillUnderDaily: z,
  pillYearRisk: x,
  pillYearSafe: I,
  pillLimitExceeded: P,
  pillLimitOk: U,
  editorDevice: K,
  editorTitle: N,
  editorClamp: Q,
  editorContractYear: j,
  editorForecast: q
};
export {
  a as badgeOk,
  s as badgeOver,
  c as badgeRisk,
  e as contractEnd,
  H as default,
  Q as editorClamp,
  j as editorContractYear,
  K as editorDevice,
  q as editorForecast,
  N as editorTitle,
  r as gaugeSub,
  i as loading,
  Y as mContractYearAllowance,
  F as mContractYearDeviation,
  f as mContractYearDriven,
  C as mDailyActual,
  b as mDeviationMonth,
  p as mDeviationToday,
  L as mForecastContractEnd,
  h as mForecastContractYear,
  R as mForecastDeviation,
  k as mRemainingContractEnd,
  T as mRemainingContractYear,
  D as mRemainingTotal,
  n as missing,
  o as noInstanceBody,
  t as noInstanceTitle,
  A as overLimit,
  P as pillLimitExceeded,
  U as pillLimitOk,
  M as pillOverDaily,
  z as pillUnderDaily,
  x as pillYearRisk,
  I as pillYearSafe,
  m as progressDays,
  l as progressLabel,
  u as sectionContractYear,
  d as sectionForecast,
  v as sectionRemaining,
  g as sectionTargetActual,
  O as subBasis30,
  w as subBasis90,
  E as subBasisTotal,
  y as subTarget,
  S as subUntilContractEnd,
  G as unknown,
  B as withinLimit
};
