const e = "Geen leasecontract gevonden", t = "Stel eerst de integratie Leasing KM Calculator in.", n = "Dit contract bestaat niet meer. Kies het opnieuw.", o = "Laden…", q = "–", a = "Einde contract {date}", i = "op schema", c = "boven doel", s = "limiet in gevaar", r = "doel {p} %", l = "Kilometers gereden", d = "{a} / {b} dagen", g = "Doel en werkelijk", m = "Contractjaar {n}", v = "Prognose", b = "Resterend op doelbasis", p = "Afwijking vandaag", k = "Afwijking einde maand", u = "Werkelijk per dag", C = "Kilometers over", j = "Gereden", w = "Afwijking", D = "Budget", T = "Einde contractjaar", h = "Einde contract", Y = "Verwacht verschil", E = "Tot einde contractjaar", L = "Tot einde contract", R = "doel {v}", y = "tot einde contract", A = "gemiddelde hele looptijd", f = "laatste 30 dagen", B = "laatste 90 dagen", F = "boven limiet", K = "binnen limiet", O = "boven dagdoel", P = "onder dagdoel", S = "jaarkilometers in gevaar", x = "jaarkilometers veilig", G = "limiet wordt overschreden", I = "limiet wordt gehaald", M = "Leasecontract", U = "Titel", z = "Percentage op 100 % begrenzen", V = "Contractjaar tonen", W = "Prognose tonen", H = {
  noInstanceTitle: e,
  noInstanceBody: t,
  missing: n,
  loading: o,
  unknown: "–",
  contractEnd: a,
  badgeOk: i,
  badgeOver: c,
  badgeRisk: s,
  gaugeSub: r,
  progressLabel: l,
  progressDays: d,
  sectionTargetActual: g,
  sectionContractYear: m,
  sectionForecast: v,
  sectionRemaining: b,
  mDeviationToday: p,
  mDeviationMonth: k,
  mDailyActual: u,
  mRemainingTotal: C,
  mContractYearDriven: j,
  mContractYearDeviation: w,
  mContractYearAllowance: D,
  mForecastContractYear: T,
  mForecastContractEnd: h,
  mForecastDeviation: Y,
  mRemainingContractYear: E,
  mRemainingContractEnd: L,
  subTarget: R,
  subUntilContractEnd: y,
  subBasisTotal: A,
  subBasis30: f,
  subBasis90: B,
  overLimit: F,
  withinLimit: K,
  pillOverDaily: O,
  pillUnderDaily: P,
  pillYearRisk: S,
  pillYearSafe: x,
  pillLimitExceeded: G,
  pillLimitOk: I,
  editorDevice: M,
  editorTitle: U,
  editorClamp: z,
  editorContractYear: V,
  editorForecast: W
};
export {
  i as badgeOk,
  c as badgeOver,
  s as badgeRisk,
  a as contractEnd,
  H as default,
  z as editorClamp,
  V as editorContractYear,
  M as editorDevice,
  W as editorForecast,
  U as editorTitle,
  r as gaugeSub,
  o as loading,
  D as mContractYearAllowance,
  w as mContractYearDeviation,
  j as mContractYearDriven,
  u as mDailyActual,
  k as mDeviationMonth,
  p as mDeviationToday,
  h as mForecastContractEnd,
  T as mForecastContractYear,
  Y as mForecastDeviation,
  L as mRemainingContractEnd,
  E as mRemainingContractYear,
  C as mRemainingTotal,
  n as missing,
  t as noInstanceBody,
  e as noInstanceTitle,
  F as overLimit,
  G as pillLimitExceeded,
  I as pillLimitOk,
  O as pillOverDaily,
  P as pillUnderDaily,
  S as pillYearRisk,
  x as pillYearSafe,
  d as progressDays,
  l as progressLabel,
  m as sectionContractYear,
  v as sectionForecast,
  b as sectionRemaining,
  g as sectionTargetActual,
  f as subBasis30,
  B as subBasis90,
  A as subBasisTotal,
  R as subTarget,
  y as subUntilContractEnd,
  q as unknown,
  K as withinLimit
};
