const e = "Geen leasecontract gevonden", t = "Stel eerst de integratie Leasing KM Calculator in.", n = "Dit contract bestaat niet meer. Kies het opnieuw.", o = "Laden…", te = "–", a = "Einde contract {date}", c = "op schema", s = "boven doel", i = "limiet in gevaar", r = "doel {p} %", l = "Kilometers gereden", d = "{a} / {b} dagen", g = "Doel en werkelijk", m = "Contractjaar {n}", v = "Prognose", b = "Resterend op doelbasis", p = "Afwijking vandaag", k = "Afwijking einde maand", C = "Werkelijk per dag", u = "Kilometers over", T = "Gereden", j = "Afwijking", w = "Budget", h = "Einde contractjaar", D = "Einde contract", f = "Verwacht verschil", A = "Tot einde contractjaar", E = "Tot einde contract", Y = "doel {v}", L = "tot einde contract", R = "gemiddelde hele looptijd", y = "laatste 30 dagen", B = "laatste 90 dagen", F = "boven limiet", K = "binnen limiet", O = "boven dagdoel", P = "onder dagdoel", x = "jaarkilometers in gevaar", S = "jaarkilometers veilig", G = "limiet wordt overschreden", I = "limiet wordt gehaald", M = "Leasecontract", U = "Titel", z = "Percentage op 100 % begrenzen", N = "Contractjaar tonen", V = "Prognose tonen", W = "Afrekening", q = "Prognose einde contract", H = "Bij normtempo", J = "Tot de tolerantie", Q = "bijbetaling verwacht", X = "vergoeding verwacht", Z = "niets af te rekenen", _ = "tolerantie aangehouden", $ = "tolerantie overschreden", ee = "Afrekening tonen", ne = {
  noInstanceTitle: e,
  noInstanceBody: t,
  missing: n,
  loading: o,
  unknown: "–",
  contractEnd: a,
  badgeOk: c,
  badgeOver: s,
  badgeRisk: i,
  gaugeSub: r,
  progressLabel: l,
  progressDays: d,
  sectionTargetActual: g,
  sectionContractYear: m,
  sectionForecast: v,
  sectionRemaining: b,
  mDeviationToday: p,
  mDeviationMonth: k,
  mDailyActual: C,
  mRemainingTotal: u,
  mContractYearDriven: T,
  mContractYearDeviation: j,
  mContractYearAllowance: w,
  mForecastContractYear: h,
  mForecastContractEnd: D,
  mForecastDeviation: f,
  mRemainingContractYear: A,
  mRemainingContractEnd: E,
  subTarget: Y,
  subUntilContractEnd: L,
  subBasisTotal: R,
  subBasis30: y,
  subBasis90: B,
  overLimit: F,
  withinLimit: K,
  pillOverDaily: O,
  pillUnderDaily: P,
  pillYearRisk: x,
  pillYearSafe: S,
  pillLimitExceeded: G,
  pillLimitOk: I,
  editorDevice: M,
  editorTitle: U,
  editorClamp: z,
  editorContractYear: N,
  editorForecast: V,
  sectionCosts: W,
  mCostForecast: q,
  mCostAtTarget: H,
  mKmToTolerance: J,
  costPay: Q,
  costRefund: X,
  costNone: Z,
  pillToleranceOk: _,
  pillToleranceExceeded: $,
  editorCosts: ee
};
export {
  c as badgeOk,
  s as badgeOver,
  i as badgeRisk,
  a as contractEnd,
  Z as costNone,
  Q as costPay,
  X as costRefund,
  ne as default,
  z as editorClamp,
  N as editorContractYear,
  ee as editorCosts,
  M as editorDevice,
  V as editorForecast,
  U as editorTitle,
  r as gaugeSub,
  o as loading,
  w as mContractYearAllowance,
  j as mContractYearDeviation,
  T as mContractYearDriven,
  H as mCostAtTarget,
  q as mCostForecast,
  C as mDailyActual,
  k as mDeviationMonth,
  p as mDeviationToday,
  D as mForecastContractEnd,
  h as mForecastContractYear,
  f as mForecastDeviation,
  J as mKmToTolerance,
  E as mRemainingContractEnd,
  A as mRemainingContractYear,
  u as mRemainingTotal,
  n as missing,
  t as noInstanceBody,
  e as noInstanceTitle,
  F as overLimit,
  G as pillLimitExceeded,
  I as pillLimitOk,
  O as pillOverDaily,
  $ as pillToleranceExceeded,
  _ as pillToleranceOk,
  P as pillUnderDaily,
  x as pillYearRisk,
  S as pillYearSafe,
  d as progressDays,
  l as progressLabel,
  m as sectionContractYear,
  W as sectionCosts,
  v as sectionForecast,
  b as sectionRemaining,
  g as sectionTargetActual,
  y as subBasis30,
  B as subBasis90,
  R as subBasisTotal,
  Y as subTarget,
  L as subUntilContractEnd,
  te as unknown,
  K as withinLimit
};
