const o = "Nie znaleziono umowy leasingowej", n = "Najpierw skonfiguruj integrację Leasing KM Calculator.", e = "Ta umowa już nie istnieje. Wybierz ją ponownie.", t = "Ładowanie…", no = "–", c = "Koniec umowy {date}", i = "zgodnie z planem", a = "powyżej celu", s = "limit zagrożony", r = "cel {p} %", l = "Przejechany przebieg", z = "{a} / {b} dni", m = "Cel i stan faktyczny", d = "Rok umowy {n}", y = "Prognoza", g = "Pozostało wg celu", u = "Odchylenie dziś", p = "Odchylenie na koniec miesiąca", w = "Faktycznie na dzień", k = "Pozostały przebieg", j = "Przejechano", b = "Odchylenie", C = "Limit", T = "Koniec roku umowy", D = "Koniec umowy", P = "Oczekiwana różnica", v = "Do końca roku umowy", O = "Do końca umowy", R = "cel {v}", Y = "do końca umowy", h = "średnia z całej umowy", F = "ostatnie 30 dni", L = "ostatnie 90 dni", E = "powyżej limitu", f = "w limicie", K = "powyżej dziennego celu", A = "poniżej dziennego celu", B = "roczny przebieg zagrożony", x = "roczny przebieg bezpieczny", N = "limit zostanie przekroczony", U = "limit dotrzymany", I = "Umowa leasingowa", M = "Tytuł", S = "Ogranicz procent do 100 %", W = "Pokaż rok umowy", q = "Pokaż prognozę", G = "Rozliczenie", H = "Prognoza na koniec umowy", J = "Przy jeździe zgodnej z celem", Q = "Do tolerancji", V = "spodziewana dopłata", X = "spodziewany zwrot", Z = "nie ma czego rozliczać", _ = "tolerancja dotrzymana", $ = "tolerancja przekroczona", oo = "Pokaż rozliczenie", eo = {
  noInstanceTitle: o,
  noInstanceBody: n,
  missing: e,
  loading: t,
  unknown: "–",
  contractEnd: c,
  badgeOk: i,
  badgeOver: a,
  badgeRisk: s,
  gaugeSub: r,
  progressLabel: l,
  progressDays: z,
  sectionTargetActual: m,
  sectionContractYear: d,
  sectionForecast: y,
  sectionRemaining: g,
  mDeviationToday: u,
  mDeviationMonth: p,
  mDailyActual: w,
  mRemainingTotal: k,
  mContractYearDriven: j,
  mContractYearDeviation: b,
  mContractYearAllowance: C,
  mForecastContractYear: T,
  mForecastContractEnd: D,
  mForecastDeviation: P,
  mRemainingContractYear: v,
  mRemainingContractEnd: O,
  subTarget: R,
  subUntilContractEnd: Y,
  subBasisTotal: h,
  subBasis30: F,
  subBasis90: L,
  overLimit: E,
  withinLimit: f,
  pillOverDaily: K,
  pillUnderDaily: A,
  pillYearRisk: B,
  pillYearSafe: x,
  pillLimitExceeded: N,
  pillLimitOk: U,
  editorDevice: I,
  editorTitle: M,
  editorClamp: S,
  editorContractYear: W,
  editorForecast: q,
  sectionCosts: G,
  mCostForecast: H,
  mCostAtTarget: J,
  mKmToTolerance: Q,
  costPay: V,
  costRefund: X,
  costNone: Z,
  pillToleranceOk: _,
  pillToleranceExceeded: $,
  editorCosts: oo
};
export {
  i as badgeOk,
  a as badgeOver,
  s as badgeRisk,
  c as contractEnd,
  Z as costNone,
  V as costPay,
  X as costRefund,
  eo as default,
  S as editorClamp,
  W as editorContractYear,
  oo as editorCosts,
  I as editorDevice,
  q as editorForecast,
  M as editorTitle,
  r as gaugeSub,
  t as loading,
  C as mContractYearAllowance,
  b as mContractYearDeviation,
  j as mContractYearDriven,
  J as mCostAtTarget,
  H as mCostForecast,
  w as mDailyActual,
  p as mDeviationMonth,
  u as mDeviationToday,
  D as mForecastContractEnd,
  T as mForecastContractYear,
  P as mForecastDeviation,
  Q as mKmToTolerance,
  O as mRemainingContractEnd,
  v as mRemainingContractYear,
  k as mRemainingTotal,
  e as missing,
  n as noInstanceBody,
  o as noInstanceTitle,
  E as overLimit,
  N as pillLimitExceeded,
  U as pillLimitOk,
  K as pillOverDaily,
  $ as pillToleranceExceeded,
  _ as pillToleranceOk,
  A as pillUnderDaily,
  B as pillYearRisk,
  x as pillYearSafe,
  z as progressDays,
  l as progressLabel,
  d as sectionContractYear,
  G as sectionCosts,
  y as sectionForecast,
  g as sectionRemaining,
  m as sectionTargetActual,
  F as subBasis30,
  L as subBasis90,
  h as subBasisTotal,
  R as subTarget,
  Y as subUntilContractEnd,
  no as unknown,
  f as withinLimit
};
