const o = "Nie znaleziono umowy leasingowej", n = "Najpierw skonfiguruj integrację Leasing KM Calculator.", t = "Ta umowa już nie istnieje. Wybierz ją ponownie.", e = "Ładowanie…", G = "–", i = "Koniec umowy {date}", c = "zgodnie z planem", a = "powyżej celu", s = "limit zagrożony", r = "cel {p} %", l = "Przejechany przebieg", m = "{a} / {b} dni", y = "Cel i stan faktyczny", d = "Rok umowy {n}", u = "Prognoza", z = "Pozostało wg celu", g = "Odchylenie dziś", p = "Odchylenie na koniec miesiąca", w = "Faktycznie na dzień", k = "Pozostały przebieg", b = "Przejechano", j = "Odchylenie", C = "Limit", D = "Koniec roku umowy", v = "Koniec umowy", O = "Oczekiwana różnica", T = "Do końca roku umowy", Y = "Do końca umowy", h = "cel {v}", L = "do końca umowy", P = "średnia z całej umowy", R = "ostatnie 30 dni", F = "ostatnie 90 dni", E = "powyżej limitu", f = "w limicie", B = "powyżej dziennego celu", K = "poniżej dziennego celu", A = "roczny przebieg zagrożony", U = "roczny przebieg bezpieczny", x = "limit zostanie przekroczony", I = "limit dotrzymany", M = "Umowa leasingowa", N = "Tytuł", S = "Ogranicz procent do 100 %", W = "Pokaż rok umowy", q = "Pokaż prognozę", H = {
  noInstanceTitle: o,
  noInstanceBody: n,
  missing: t,
  loading: e,
  unknown: "–",
  contractEnd: i,
  badgeOk: c,
  badgeOver: a,
  badgeRisk: s,
  gaugeSub: r,
  progressLabel: l,
  progressDays: m,
  sectionTargetActual: y,
  sectionContractYear: d,
  sectionForecast: u,
  sectionRemaining: z,
  mDeviationToday: g,
  mDeviationMonth: p,
  mDailyActual: w,
  mRemainingTotal: k,
  mContractYearDriven: b,
  mContractYearDeviation: j,
  mContractYearAllowance: C,
  mForecastContractYear: D,
  mForecastContractEnd: v,
  mForecastDeviation: O,
  mRemainingContractYear: T,
  mRemainingContractEnd: Y,
  subTarget: h,
  subUntilContractEnd: L,
  subBasisTotal: P,
  subBasis30: R,
  subBasis90: F,
  overLimit: E,
  withinLimit: f,
  pillOverDaily: B,
  pillUnderDaily: K,
  pillYearRisk: A,
  pillYearSafe: U,
  pillLimitExceeded: x,
  pillLimitOk: I,
  editorDevice: M,
  editorTitle: N,
  editorClamp: S,
  editorContractYear: W,
  editorForecast: q
};
export {
  c as badgeOk,
  a as badgeOver,
  s as badgeRisk,
  i as contractEnd,
  H as default,
  S as editorClamp,
  W as editorContractYear,
  M as editorDevice,
  q as editorForecast,
  N as editorTitle,
  r as gaugeSub,
  e as loading,
  C as mContractYearAllowance,
  j as mContractYearDeviation,
  b as mContractYearDriven,
  w as mDailyActual,
  p as mDeviationMonth,
  g as mDeviationToday,
  v as mForecastContractEnd,
  D as mForecastContractYear,
  O as mForecastDeviation,
  Y as mRemainingContractEnd,
  T as mRemainingContractYear,
  k as mRemainingTotal,
  t as missing,
  n as noInstanceBody,
  o as noInstanceTitle,
  E as overLimit,
  x as pillLimitExceeded,
  I as pillLimitOk,
  B as pillOverDaily,
  K as pillUnderDaily,
  A as pillYearRisk,
  U as pillYearSafe,
  m as progressDays,
  l as progressLabel,
  d as sectionContractYear,
  u as sectionForecast,
  z as sectionRemaining,
  y as sectionTargetActual,
  R as subBasis30,
  F as subBasis90,
  P as subBasisTotal,
  h as subTarget,
  L as subUntilContractEnd,
  G as unknown,
  f as withinLimit
};
