const o = "Nenhum contrato de leasing encontrado", t = "Configure primeiro a integração Leasing KM Calculator.", e = "Este contrato já não existe. Selecione-o novamente.", n = "A carregar…", to = "–", a = "Fim do contrato {date}", i = "dentro do previsto", s = "acima do objetivo", c = "limite em risco", r = "objetivo {p} %", d = "Quilometragem percorrida", m = "{a} / {b} dias", l = "Objetivo e real", g = "Ano de contrato {n}", v = "Previsão", p = "Restante na base do objetivo", u = "Desvio hoje", b = "Desvio no fim do mês", C = "Real por dia", D = "Quilómetros restantes", T = "Percorrido", A = "Desvio", f = "Limite", j = "Fim do ano de contrato", F = "Fim do contrato", R = "Diferença esperada", Y = "Até ao fim do ano de contrato", L = "Até ao fim do contrato", k = "objetivo {v}", x = "até ao fim do contrato", y = "média de todo o contrato", E = "últimos 30 dias", O = "últimos 90 dias", M = "acima do limite", h = "dentro do limite", w = "acima do objetivo diário", B = "abaixo do objetivo diário", P = "quilometragem anual em risco", S = "quilometragem anual segura", q = "o limite será excedido", I = "limite cumprido", K = "Contrato de leasing", N = "Título", Q = "Limitar a percentagem a 100 %", U = "Mostrar o ano de contrato", z = "Mostrar a previsão", G = "Acerto", H = "Previsão fim do contrato", J = "Ao ritmo do objetivo", V = "Até à tolerância", W = "pagamento previsto", X = "reembolso previsto", Z = "nada a acertar", _ = "tolerância cumprida", $ = "tolerância excedida", oo = "Mostrar o acerto", eo = {
  noInstanceTitle: o,
  noInstanceBody: t,
  missing: e,
  loading: n,
  unknown: "–",
  contractEnd: a,
  badgeOk: i,
  badgeOver: s,
  badgeRisk: c,
  gaugeSub: r,
  progressLabel: d,
  progressDays: m,
  sectionTargetActual: l,
  sectionContractYear: g,
  sectionForecast: v,
  sectionRemaining: p,
  mDeviationToday: u,
  mDeviationMonth: b,
  mDailyActual: C,
  mRemainingTotal: D,
  mContractYearDriven: T,
  mContractYearDeviation: A,
  mContractYearAllowance: f,
  mForecastContractYear: j,
  mForecastContractEnd: F,
  mForecastDeviation: R,
  mRemainingContractYear: Y,
  mRemainingContractEnd: L,
  subTarget: k,
  subUntilContractEnd: x,
  subBasisTotal: y,
  subBasis30: E,
  subBasis90: O,
  overLimit: M,
  withinLimit: h,
  pillOverDaily: w,
  pillUnderDaily: B,
  pillYearRisk: P,
  pillYearSafe: S,
  pillLimitExceeded: q,
  pillLimitOk: I,
  editorDevice: K,
  editorTitle: N,
  editorClamp: Q,
  editorContractYear: U,
  editorForecast: z,
  sectionCosts: G,
  mCostForecast: H,
  mCostAtTarget: J,
  mKmToTolerance: V,
  costPay: W,
  costRefund: X,
  costNone: Z,
  pillToleranceOk: _,
  pillToleranceExceeded: $,
  editorCosts: oo
};
export {
  i as badgeOk,
  s as badgeOver,
  c as badgeRisk,
  a as contractEnd,
  Z as costNone,
  W as costPay,
  X as costRefund,
  eo as default,
  Q as editorClamp,
  U as editorContractYear,
  oo as editorCosts,
  K as editorDevice,
  z as editorForecast,
  N as editorTitle,
  r as gaugeSub,
  n as loading,
  f as mContractYearAllowance,
  A as mContractYearDeviation,
  T as mContractYearDriven,
  J as mCostAtTarget,
  H as mCostForecast,
  C as mDailyActual,
  b as mDeviationMonth,
  u as mDeviationToday,
  F as mForecastContractEnd,
  j as mForecastContractYear,
  R as mForecastDeviation,
  V as mKmToTolerance,
  L as mRemainingContractEnd,
  Y as mRemainingContractYear,
  D as mRemainingTotal,
  e as missing,
  t as noInstanceBody,
  o as noInstanceTitle,
  M as overLimit,
  q as pillLimitExceeded,
  I as pillLimitOk,
  w as pillOverDaily,
  $ as pillToleranceExceeded,
  _ as pillToleranceOk,
  B as pillUnderDaily,
  P as pillYearRisk,
  S as pillYearSafe,
  m as progressDays,
  d as progressLabel,
  g as sectionContractYear,
  G as sectionCosts,
  v as sectionForecast,
  p as sectionRemaining,
  l as sectionTargetActual,
  E as subBasis30,
  O as subBasis90,
  y as subBasisTotal,
  k as subTarget,
  x as subUntilContractEnd,
  to as unknown,
  h as withinLimit
};
