const o = "Nenhum contrato de leasing encontrado", t = "Configure primeiro a integração Leasing KM Calculator.", n = "Este contrato já não existe. Selecione-o novamente.", e = "A carregar…", G = "–", a = "Fim do contrato {date}", i = "dentro do previsto", s = "acima do objetivo", c = "limite em risco", r = "objetivo {p} %", d = "Quilometragem percorrida", m = "{a} / {b} dias", l = "Objetivo e real", g = "Ano de contrato {n}", u = "Previsão", v = "Restante na base do objetivo", b = "Desvio hoje", p = "Desvio no fim do mês", C = "Real por dia", D = "Quilómetros restantes", j = "Percorrido", Y = "Desvio", f = "Limite", F = "Fim do ano de contrato", L = "Fim do contrato", R = "Diferença esperada", T = "Até ao fim do ano de contrato", A = "Até ao fim do contrato", k = "objetivo {v}", y = "até ao fim do contrato", E = "média de todo o contrato", x = "últimos 30 dias", O = "últimos 90 dias", h = "acima do limite", w = "dentro do limite", B = "acima do objetivo diário", M = "abaixo do objetivo diário", S = "quilometragem anual em risco", q = "quilometragem anual segura", I = "o limite será excedido", P = "limite cumprido", Q = "Contrato de leasing", U = "Título", K = "Limitar a percentagem a 100 %", N = "Mostrar o ano de contrato", z = "Mostrar a previsão", H = {
  noInstanceTitle: o,
  noInstanceBody: t,
  missing: n,
  loading: e,
  unknown: "–",
  contractEnd: a,
  badgeOk: i,
  badgeOver: s,
  badgeRisk: c,
  gaugeSub: r,
  progressLabel: d,
  progressDays: m,
  sectionTargetActual: l,
  sectionContractYear: g,
  sectionForecast: u,
  sectionRemaining: v,
  mDeviationToday: b,
  mDeviationMonth: p,
  mDailyActual: C,
  mRemainingTotal: D,
  mContractYearDriven: j,
  mContractYearDeviation: Y,
  mContractYearAllowance: f,
  mForecastContractYear: F,
  mForecastContractEnd: L,
  mForecastDeviation: R,
  mRemainingContractYear: T,
  mRemainingContractEnd: A,
  subTarget: k,
  subUntilContractEnd: y,
  subBasisTotal: E,
  subBasis30: x,
  subBasis90: O,
  overLimit: h,
  withinLimit: w,
  pillOverDaily: B,
  pillUnderDaily: M,
  pillYearRisk: S,
  pillYearSafe: q,
  pillLimitExceeded: I,
  pillLimitOk: P,
  editorDevice: Q,
  editorTitle: U,
  editorClamp: K,
  editorContractYear: N,
  editorForecast: z
};
export {
  i as badgeOk,
  s as badgeOver,
  c as badgeRisk,
  a as contractEnd,
  H as default,
  K as editorClamp,
  N as editorContractYear,
  Q as editorDevice,
  z as editorForecast,
  U as editorTitle,
  r as gaugeSub,
  e as loading,
  f as mContractYearAllowance,
  Y as mContractYearDeviation,
  j as mContractYearDriven,
  C as mDailyActual,
  p as mDeviationMonth,
  b as mDeviationToday,
  L as mForecastContractEnd,
  F as mForecastContractYear,
  R as mForecastDeviation,
  A as mRemainingContractEnd,
  T as mRemainingContractYear,
  D as mRemainingTotal,
  n as missing,
  t as noInstanceBody,
  o as noInstanceTitle,
  h as overLimit,
  I as pillLimitExceeded,
  P as pillLimitOk,
  B as pillOverDaily,
  M as pillUnderDaily,
  S as pillYearRisk,
  q as pillYearSafe,
  m as progressDays,
  d as progressLabel,
  g as sectionContractYear,
  u as sectionForecast,
  v as sectionRemaining,
  l as sectionTargetActual,
  x as subBasis30,
  O as subBasis90,
  E as subBasisTotal,
  k as subTarget,
  y as subUntilContractEnd,
  G as unknown,
  w as withinLimit
};
