const t = "Inget leasingavtal hittades", n = "Konfigurera först integrationen Leasing KM Calculator.", s = "Det här avtalet finns inte längre. Välj det igen.", a = "Läser in…", H = "–", e = "Avtalet slutar {date}", o = "enligt plan", i = "över mål", r = "gränsen i fara", c = "mål {p} %", l = "Körd sträcka", g = "{a} / {b} dagar", d = "Mål och faktiskt", v = "Avtalsår {n}", m = "Prognos", k = "Återstår enligt mål", u = "Avvikelse i dag", p = "Avvikelse vid månadsskiftet", C = "Faktiskt per dag", b = "Kilometer kvar", D = "Kört", f = "Avvikelse", A = "Gräns", T = "Avtalsårets slut", Y = "Avtalets slut", L = "Förväntad skillnad", h = "Till avtalsårets slut", F = "Till avtalets slut", y = "mål {v}", R = "till avtalets slut", B = "genomsnitt för hela avtalet", E = "senaste 30 dagarna", K = "senaste 90 dagarna", w = "över gränsen", O = "inom gränsen", I = "över dagsmålet", M = "under dagsmålet", V = "årlig körsträcka i fara", x = "årlig körsträcka säker", S = "gränsen kommer att överskridas", U = "gränsen hålls", j = "Leasingavtal", G = "Titel", P = "Begränsa procenten till 100 %", q = "Visa avtalsår", z = "Visa prognos", J = {
  noInstanceTitle: t,
  noInstanceBody: n,
  missing: s,
  loading: a,
  unknown: "–",
  contractEnd: e,
  badgeOk: o,
  badgeOver: i,
  badgeRisk: r,
  gaugeSub: c,
  progressLabel: l,
  progressDays: g,
  sectionTargetActual: d,
  sectionContractYear: v,
  sectionForecast: m,
  sectionRemaining: k,
  mDeviationToday: u,
  mDeviationMonth: p,
  mDailyActual: C,
  mRemainingTotal: b,
  mContractYearDriven: D,
  mContractYearDeviation: f,
  mContractYearAllowance: A,
  mForecastContractYear: T,
  mForecastContractEnd: Y,
  mForecastDeviation: L,
  mRemainingContractYear: h,
  mRemainingContractEnd: F,
  subTarget: y,
  subUntilContractEnd: R,
  subBasisTotal: B,
  subBasis30: E,
  subBasis90: K,
  overLimit: w,
  withinLimit: O,
  pillOverDaily: I,
  pillUnderDaily: M,
  pillYearRisk: V,
  pillYearSafe: x,
  pillLimitExceeded: S,
  pillLimitOk: U,
  editorDevice: j,
  editorTitle: G,
  editorClamp: P,
  editorContractYear: q,
  editorForecast: z
};
export {
  o as badgeOk,
  i as badgeOver,
  r as badgeRisk,
  e as contractEnd,
  J as default,
  P as editorClamp,
  q as editorContractYear,
  j as editorDevice,
  z as editorForecast,
  G as editorTitle,
  c as gaugeSub,
  a as loading,
  A as mContractYearAllowance,
  f as mContractYearDeviation,
  D as mContractYearDriven,
  C as mDailyActual,
  p as mDeviationMonth,
  u as mDeviationToday,
  Y as mForecastContractEnd,
  T as mForecastContractYear,
  L as mForecastDeviation,
  F as mRemainingContractEnd,
  h as mRemainingContractYear,
  b as mRemainingTotal,
  s as missing,
  n as noInstanceBody,
  t as noInstanceTitle,
  w as overLimit,
  S as pillLimitExceeded,
  U as pillLimitOk,
  I as pillOverDaily,
  M as pillUnderDaily,
  V as pillYearRisk,
  x as pillYearSafe,
  g as progressDays,
  l as progressLabel,
  v as sectionContractYear,
  m as sectionForecast,
  k as sectionRemaining,
  d as sectionTargetActual,
  E as subBasis30,
  K as subBasis90,
  B as subBasisTotal,
  y as subTarget,
  R as subUntilContractEnd,
  H as unknown,
  O as withinLimit
};
