const t = "Inget leasingavtal hittades", n = "Konfigurera först integrationen Leasing KM Calculator.", s = "Det här avtalet finns inte längre. Välj det igen.", a = "Läser in…", nt = "–", e = "Avtalet slutar {date}", o = "enligt plan", r = "över mål", i = "gränsen i fara", l = "mål {p} %", c = "Körd sträcka", g = "{a} / {b} dagar", v = "Mål och faktiskt", d = "Avtalsår {n}", m = "Prognos", k = "Återstår enligt mål", u = "Avvikelse i dag", p = "Avvikelse vid månadsskiftet", C = "Faktiskt per dag", T = "Kilometer kvar", b = "Kört", A = "Avvikelse", f = "Gräns", D = "Avtalsårets slut", Y = "Avtalets slut", h = "Förväntad skillnad", F = "Till avtalsårets slut", L = "Till avtalets slut", y = "mål {v}", R = "till avtalets slut", E = "genomsnitt för hela avtalet", K = "senaste 30 dagarna", B = "senaste 90 dagarna", O = "över gränsen", V = "inom gränsen", w = "över dagsmålet", x = "under dagsmålet", I = "årlig körsträcka i fara", M = "årlig körsträcka säker", P = "gränsen kommer att överskridas", S = "gränsen hålls", U = "Leasingavtal", j = "Titel", G = "Begränsa procenten till 100 %", N = "Visa avtalsår", q = "Visa prognos", z = "Avräkning", H = "Prognos vid avtalets slut", J = "Vid måltakt", Q = "Till toleransen", W = "tilläggsbetalning väntas", X = "ersättning väntas", Z = "inget att avräkna", _ = "toleransen hålls", $ = "toleransen överskriden", tt = "Visa avräkning", st = {
  noInstanceTitle: t,
  noInstanceBody: n,
  missing: s,
  loading: a,
  unknown: "–",
  contractEnd: e,
  badgeOk: o,
  badgeOver: r,
  badgeRisk: i,
  gaugeSub: l,
  progressLabel: c,
  progressDays: g,
  sectionTargetActual: v,
  sectionContractYear: d,
  sectionForecast: m,
  sectionRemaining: k,
  mDeviationToday: u,
  mDeviationMonth: p,
  mDailyActual: C,
  mRemainingTotal: T,
  mContractYearDriven: b,
  mContractYearDeviation: A,
  mContractYearAllowance: f,
  mForecastContractYear: D,
  mForecastContractEnd: Y,
  mForecastDeviation: h,
  mRemainingContractYear: F,
  mRemainingContractEnd: L,
  subTarget: y,
  subUntilContractEnd: R,
  subBasisTotal: E,
  subBasis30: K,
  subBasis90: B,
  overLimit: O,
  withinLimit: V,
  pillOverDaily: w,
  pillUnderDaily: x,
  pillYearRisk: I,
  pillYearSafe: M,
  pillLimitExceeded: P,
  pillLimitOk: S,
  editorDevice: U,
  editorTitle: j,
  editorClamp: G,
  editorContractYear: N,
  editorForecast: q,
  sectionCosts: z,
  mCostForecast: H,
  mCostAtTarget: J,
  mKmToTolerance: Q,
  costPay: W,
  costRefund: X,
  costNone: Z,
  pillToleranceOk: _,
  pillToleranceExceeded: $,
  editorCosts: tt
};
export {
  o as badgeOk,
  r as badgeOver,
  i as badgeRisk,
  e as contractEnd,
  Z as costNone,
  W as costPay,
  X as costRefund,
  st as default,
  G as editorClamp,
  N as editorContractYear,
  tt as editorCosts,
  U as editorDevice,
  q as editorForecast,
  j as editorTitle,
  l as gaugeSub,
  a as loading,
  f as mContractYearAllowance,
  A as mContractYearDeviation,
  b as mContractYearDriven,
  J as mCostAtTarget,
  H as mCostForecast,
  C as mDailyActual,
  p as mDeviationMonth,
  u as mDeviationToday,
  Y as mForecastContractEnd,
  D as mForecastContractYear,
  h as mForecastDeviation,
  Q as mKmToTolerance,
  L as mRemainingContractEnd,
  F as mRemainingContractYear,
  T as mRemainingTotal,
  s as missing,
  n as noInstanceBody,
  t as noInstanceTitle,
  O as overLimit,
  P as pillLimitExceeded,
  S as pillLimitOk,
  w as pillOverDaily,
  $ as pillToleranceExceeded,
  _ as pillToleranceOk,
  x as pillUnderDaily,
  I as pillYearRisk,
  M as pillYearSafe,
  g as progressDays,
  c as progressLabel,
  d as sectionContractYear,
  z as sectionCosts,
  m as sectionForecast,
  k as sectionRemaining,
  v as sectionTargetActual,
  K as subBasis30,
  B as subBasis90,
  E as subBasisTotal,
  y as subTarget,
  R as subUntilContractEnd,
  nt as unknown,
  V as withinLimit
};
